# ~/crowdfunding/projects/api_urls.py (Recommended location)

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .api_views import ProjectViewSet 

router = DefaultRouter()
# Register ProjectViewSet with an empty prefix for the root of the API path
# The basename 'project' will be used to generate URL names like 'project-list', 'project-detail', etc.
router.register(r'', ProjectViewSet, basename='project')

# The API URLs are now determined automatically by the router.
urlpatterns = [
    # This line includes all URLs generated by the router
    # For example:
    # /api/projects/ (list)
    # /api/projects/{id}/ (detail)
    # /api/projects/{id}/donate/ (custom action)
    # etc.
    path('', include(router.urls)),
]

