# Generated by Django 5.2.3 on 2025-06-27 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='project',
            name='rating_count',
        ),
        migrations.AlterField(
            model_name='projectpicture',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures', to='projects.project'),
        ),
        migrations.DeleteModel(
            name='CommentReport',
        ),
    ]
